# Task 1:Repeat Purchase Prediction using Machine Learning.

## Purpose: To predict whether a customer will make another purchase within the next 30 days or not.

# Create Dataset

In [13]:
# Import Libraries & Dataset
import pandas as pd

data = {
    "customer_id": list(range(1, 11)),

    "order_count_last_90d": [5,2,8,1,4,6,3,7,2,5],

    "avg_order_value": [500,200,800,150,400,650,300,900,250,550],

    "days_since_last_order": [10,40,5,60,20,15,35,7,50,12],

    "repeat_purchase_flag": [1,0,1,0,1,1,0,1,0,1],

    "discount_used_on_repeat_order": [50,0,30,0,20,40,0,25,0,35]
}

df = pd.DataFrame(data)
df

,customer_id,order_count_last_90d,avg_order_value,days_since_last_order,repeat_purchase_flag,discount_used_on_repeat_order
0,1,5,500,10,1,50
1,2,2,200,40,0,0
2,3,8,800,5,1,30
3,4,1,150,60,0,0
4,5,4,400,20,1,20
5,6,6,650,15,1,40
6,7,3,300,35,0,0
7,8,7,900,7,1,25
8,9,2,250,50,0,0
9,10,5,550,12,1,35

In [14]:
df.style.hide(axis="index")

# Task 2: Machine Learning Data Preparation

## Purpose: To clean the data, remove leakage, and split it into training and testing sets before model training.

###Step 1: Identify the target variable for prediction.

 ### Removing unnecessary or non-informative features from the dataset

In [15]:
#Identify Label & Data Leakage

label = "repeat_purchase_flag"
leakage_column = "discount_used_on_repeat_order"

### Result:
- Target variable identified successfully  
- Irrelevant features removed

### Step 2: Remove Leakage Column

In [16]:
df = df.drop(columns=[leakage_column])
df

,customer_id,order_count_last_90d,avg_order_value,days_since_last_order,repeat_purchase_flag
0,1,5,500,10,1
1,2,2,200,40,0
2,3,8,800,5,1
3,4,1,150,60,0
4,5,4,400,20,1
5,6,6,650,15,1
6,7,3,300,35,0
7,8,7,900,7,1
8,9,2,250,50,0
9,10,5,550,12,1

Result: The column is removed successfully

### Step 3: Define Features (X) and Target (y)

In [17]:
X = df.drop(columns=[label])
y = df[label]

Result: X aur y properly split

### Step 5: Train-Test Split

In [18]:
# The model is receiving training and testing data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Step 6: Train Model

In [19]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()
model.fit(X_train, y_train)

GradientBoostingClassifier()

Result:Model trained successfully

### Step 7: Make Predictions

In [20]:
y_pred = model.predict(X_test)
y_pred

array([0, 0])

In [21]:
len(X_test)

2

In [22]:
y_test.values

array([0, 0])

Result: The model predictions match the actual values in the test set

### Step 8: Check Accuracy

In [23]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

Result: Test samples were predicted correctly